#!/bin/bash


#Behave variables
#  -default tests run with mininet
#  -for openStack tests set BH_VAR_OPENSTACK=true
#  -BH_LOG can be OUTPUT (default) for normal output and WARNING which will suppress normal output
#  -BH_LOG also sets mininet loglevel
#  -BH_CONTROLLER_TYPE tells behave which controller is beeing under test. REMOTE is default.
#  -BH_CONTROLLER_IP_PORT holds ip and port for chosen controller
export BH_LOG='OUTPUT'
export BH_OPENSTACK=false
export BH_CONTROLLER_TYPE='ONOS'
export BH_CONTROLLER_IP_PORT='192.168.0.102'



# reset previous set username and password
unset TF_VAR_os_user
unset TF_VAR_os_password
unset TF_VAR_os_project

# parse parameters
for i in "$@"
do
case $i in
  --help*)
  PRINT_USAGE=1
  shift
  ;;
  *)
  PRINT_USAGE=1;
  echo "error: unknown option ${i#*}. Type --help."
  ;;
esac
done

# print usage
if [ ! -z ${PRINT_USAGE+1} ]; then
  echo "Usage: source config"
  echo "Edit the File with all necessary settings. You will be prompted for openstack credentials."
  # -INT behaves like STRG+C
  kill -INT $$
fi

if [ ${BH_OPENSTACK} == true ]; then
  # user name and password dialog
  if [ -z ${INPUT_USERNAME+1} ]; then
    echo -n "Enter openStack username (LS3-LDAP): "
    read INPUT_USERNAME
  fi
  if [ -z ${INPUT_PASSWORD+1} ]; then
    echo -n "Enter OpenStack password (hidden input): "
    read -sr INPUT_PASSWORD
    echo
  fi
  echo "[OK]: Authentication temporary stored."
else
  echo "[OK]: Settings temporary stored."
fi

if [ ${BH_OPENSTACK} == true ]; then
  # openstack environment variables you will be prompted for:
  export TF_VAR_os_user=$INPUT_USERNAME
  export TF_VAR_os_password=$INPUT_PASSWORD

  # openstack environment variables you need to set in this file:
  export TF_VAR_os_auth_url='https://172.17.0.3:5000/v3'
  export TF_VAR_os_project='user-benedikt.pfaff'
  export TF_VAR_os_domain_name='lsinfo3'
  export TF_VAR_os_user_domain_name='lsinfo3'

  # additional openStack variables (used for python-os/neutron-client)
  export LC_ALL=C
  export OS_IDENTITY_API_VERSION=3
  export OS_PROJECT_NAME='user-benedikt.pfaff'
  export OS_USER_DOMAIN_NAME='lsinfo3'
  export OS_PROJECT_DOMAIN_NAME='lsinfo3'
  export OS_USERNAME=$INPUT_USERNAME
  export OS_PASSWORD=$INPUT_PASSWORD
  export OS_AUTH_URL='https://ls3cloud1.informatik.uni-wuerzburg.de:5000/v3/'
  export OS_AUTH_STRATEGY='keystone'
  export OS_REGION_NAME='RegionOne'
  export OS_CACERT='ls3cloud1.pem'
  export CINDER_ENDPOINT_TYPE='public'
  export GLANCE_ENDPOINT_TYPE='public'
  export KEYSTONE_ENDPOINT_TYPE='public'
  export NOVA_ENDPOINT_TYPE='public'
  export NEUTRON_ENDPOINT_TYPE='public'
  export OS_ENDPOINT_TYPE='public'
  export OS_INTERFACE='public'
  export MURANO_REPO_URL='http://storage.apps.openstack.org/'
fi

# this is required to export aliases for other scripts
shopt -s expand_aliases

